blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation & Customer Hub
    url: https://hub.relution.io
    about: Find documentation, changelogs and known issues of Relution
  - name: ğŸ« Commercial Support
    url: https://helpdesk.relution.io
    about: For Relution customers to open a support ticket
  - name: ğŸ—£ï¸ Community Forum
    url: https://community.relution.io
    about: Engage with the Relution community
  - name: ğŸ”’ Security Contact
    url: mailto:security@relution.io
    about: Report security vulnerabilities